# Generated by Django 5.1.3 on 2024-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
